package:
  - datetime  #　导入额外的包，在jinja2模板中使用（下面有用到datetime包，所以要先导入）
env:
  time_format:
    engine: eq
    rule:
      value: "%Y-%m-%d %H:%M:%S"
tables:
- table: stu
  comment: '学生表'
  columns:
    id:
      comment: 数据主键id
      engine: eq('{{ env.id }}') # 通过引用环境变量中的值
    name:
      comment: 姓名
      engine: name
    idcard:
      comment: 身份证号
      engine: ssn
    age:
      comment: 年龄
      engine: eq('{{ datetime.datetime.now().year - int(stu.idcard[6:10]) }}') #　通过jinja２模板直接计算
    sex:
      comment: 性别
      engine: faker.eq('{{ "man" if int(stu.idcard[-2]) % 2==1 else "female" }}')  #　通过jinja２模板直接计算
- table: course
  comment: '课程表'
  columns:
    id:
      comment: 数据主键id
      engine: faker.uuid
    stu_id:
      comment: 数据主键id
      engine: faker.eq('{{ stu.id }}') # 引用其他表中的值
    course_name:
      comment: 课程名称
      engine: faker.choice(['数学','语文','英语','化学','地理']) # 通过内置方法从列表中随机取一个值
    course_time:
      comment: 上课时间
      engine: faker.now(format="{{ env.time_format }}")  # 通过内置方法获取当前时间，并按照指定格式返回
extraction:
  stu_name:
    value: '{{ stu.name }}'
  course_name:
    value: '{{ course.course_name }}'